"use client";

import useSWR from "swr";
import { toast } from "sonner";
import {
  Clock,
  Layers,
  Globe,
  DollarSign,
  TrendingDown,
  Share2,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface RoiData {
  timeSavedMinutes: number;
  contentPiecesGenerated: number;
  platformReach: number;
  costPerClip: number;
  manualCost: number;
}

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const formatNumber = (n: number): string => {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toLocaleString();
};

const formatCurrency = (n: number): string => {
  return `$${n.toFixed(2)}`;
};

export function RoiSection() {
  const { data, error, isLoading } = useSWR<RoiData>(
    "/api/analytics/roi",
    fetcher
  );

  const handleShareWithLeadership = () => {
    if (!data) return;

    const savings = data.manualCost - data.costPerClip * data.contentPiecesGenerated;
    const text = [
      "Sermon Clips ROI Report",
      "========================",
      "",
      `Time Saved: ${data.timeSavedMinutes} minutes`,
      `Content Pieces Generated: ${data.contentPiecesGenerated}`,
      `Platform Reach: ${formatNumber(data.platformReach)}`,
      `Cost Per Clip: ${formatCurrency(data.costPerClip)}`,
      `vs. Manual Cost: ${formatCurrency(data.manualCost)}`,
      `Total Savings: ${formatCurrency(savings > 0 ? savings : 0)}`,
      "",
      "Generated by Sermon Clips",
    ].join("\n");

    navigator.clipboard.writeText(text).then(
      () => toast.success("Report copied to clipboard"),
      () => toast.error("Failed to copy to clipboard")
    );
  };

  if (isLoading) {
    return (
      <Card className="border-[#E8E4DC] bg-[#F5F1EB]">
        <CardContent className="p-6">
          <div className="flex items-center justify-center py-8 text-[#2D2D2D]/50">
            Loading ROI data...
          </div>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className="border-[#E8E4DC] bg-[#F5F1EB]">
        <CardContent className="p-6">
          <div className="flex items-center justify-center py-8 text-red-500">
            Failed to load ROI data
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!data) return null;

  const metrics = [
    {
      label: "Time Saved",
      value: `${data.timeSavedMinutes}`,
      unit: "minutes",
      icon: <Clock className="h-5 w-5" />,
      color: "text-blue-500",
      bgColor: "bg-blue-50",
    },
    {
      label: "Content Pieces Generated",
      value: formatNumber(data.contentPiecesGenerated),
      unit: "pieces",
      icon: <Layers className="h-5 w-5" />,
      color: "text-[#E8725A]",
      bgColor: "bg-[#E8725A]/5",
    },
    {
      label: "Platform Reach",
      value: formatNumber(data.platformReach),
      unit: "impressions",
      icon: <Globe className="h-5 w-5" />,
      color: "text-emerald-500",
      bgColor: "bg-emerald-50",
    },
    {
      label: "Cost Per Clip",
      value: formatCurrency(data.costPerClip),
      unit: "",
      icon: <DollarSign className="h-5 w-5" />,
      color: "text-amber-500",
      bgColor: "bg-amber-50",
    },
    {
      label: "vs. Manual Cost",
      value: formatCurrency(data.manualCost),
      unit: "estimated",
      icon: <TrendingDown className="h-5 w-5" />,
      color: "text-purple-500",
      bgColor: "bg-purple-50",
    },
  ];

  return (
    <Card className="border-[#E8E4DC] bg-[#F5F1EB]">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-[#2D2D2D] flex items-center gap-2">
              <TrendingDown className="h-5 w-5 text-[#E8725A]" />
              ROI Dashboard
            </CardTitle>
            <CardDescription className="text-[#2D2D2D]/60">
              See how Sermon Clips saves your team time and money
            </CardDescription>
          </div>
          <Button
            variant="secondary"
            size="sm"
            onClick={handleShareWithLeadership}
            className="border-[#E8E4DC] text-[#2D2D2D]/70 hover:border-[#E8725A] hover:text-[#E8725A]"
          >
            <Share2 className="h-4 w-4 mr-1.5" />
            Share with Leadership
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {metrics.map((metric) => (
            <Card
              key={metric.label}
              className="border-[#E8E4DC] bg-white shadow-none"
            >
              <CardContent className="p-4">
                <div className="flex items-start gap-3">
                  <div
                    className={`p-2 rounded-lg ${metric.bgColor} ${metric.color} shrink-0`}
                  >
                    {metric.icon}
                  </div>
                  <div className="min-w-0">
                    <p className="text-2xl font-bold text-[#2D2D2D]">
                      {metric.value}
                    </p>
                    {metric.unit && (
                      <p className="text-xs text-[#2D2D2D]/40 -mt-0.5">
                        {metric.unit}
                      </p>
                    )}
                    <p className="text-sm text-[#2D2D2D]/60 mt-1">
                      {metric.label}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
